### ISSUE TITLE
Implement the billing schedule functionality (config entity, plugins)

### ISSUE THREAD

**Issue by dawehner** [bojanz/commerce_recurring#1]
> but our first one is to create a BillingSchedule config entity + plugin combo like in Commerce (checkout flows, payment gateways, tax types)
> where we can configure the payment type (prepayment/postpayment), asynchronous/synchronous, and the actual interval/period (monthly, yearly, etc)

**Comment by bojanz** [comment]
D7 version of the code: http://cgit.drupalcode.org/commerce_license_billing/tree/plugins/billing_cycle_engine/base.inc
http://cgit.drupalcode.org/commerce_license_billing/tree/plugins/billing_cycle_engine/CommerceLicenseBillingCycleTypePeriodic.class.php

D8 code of interest:
http://cgit.drupalcode.org/recurring_period/tree/src/Plugin/RecurringPeriod/RollingInterval.php

**Comment by dawehner** [comment]
I would argue at that point this is resolved. We might need adaptions, but the general architecture is done.
