### ISSUE TITLE
Allow charging a different price for the initial billing cycle

### ISSUE THREAD

**Issue by bojanz** [bojanz/commerce_recurring#11]
This might be a more generic way to do #3 (free trials) as well, depends on whether we decide to invoice free trials (which probably makes sense)

**Comment by bojanz** [comment]
Okay, definitely a different thing, since trials happen before the first billing cycle, and this is about having a different price for the first billing cycle.

We have two options here:
1) Ask for an initial price to be configured, per currency, on the billing schedule config entity.
2) Store an initial_price on the subscription, along with the regular price, and rely on custom code to map it from 1 or N variation price fields.

The problem with #1 is that it ties a billing schedule to a specific plan, the entity becomes less reusable.
The problem with #2 is that setting a different billing cycle price ends up being a task that requires custom code.

I am currently leaning towards #2 + documentation. https://www.drupal.org/node/2914245 would also help there.

**Comment by wizonesolutions** [comment]
Re. # 2 — custom code implies a custom price resolver, I guess? It might be neat to have the regular price available in the object, e.g. if someone wants to show the customer that they are getting a discount on the invoice.

**Comment by bojanz** [comment]
Left to custom code for now.
