### ISSUE TITLE
Implement retry functionality for soft payment failures

### ISSUE THREAD

**Issue by bojanz** [bojanz/commerce_recurring#13]
We need to identify soft payment failures (usually caused by the attached payment method being temporarily unavailable, reached daily limit, etc) and schedule retries. The number of retries needs to be configurable. We need to fire events on retries / giving up, to allow dunning emails to be hooked in.

Initial discussions with Kazanir ended with the conclusion that we should use advancedqueue with created dates in the future to handle this scheduling.

**Comment by wizonesolutions** [comment]
Will you have a sort of linked list among the AdvancedQueue entries, or perhaps a multi-value reference field on the order or some kind of common tag on each entry? Such that when the payment goes through, you can cancel further follow-ups.

**Comment by bojanz** [comment]
Advanced queue items are not entities, so referencing them would be pretty ugly.
Might be okay to let them happen anyway, but make the queue workers exit early if they see that the order was successfully closed in the meantime.

**Comment by wizonesolutions** [comment]
True, that could work too. And perhaps that sort of standalone benefit
behavior would be easiest to reason about.

14. okt. 2017 23:01 je oseba "Bojan Zivanovic" <notifications@github.com>
napisala:

**Comment by bojanz** [comment]
Now tracked on d.o: https://www.drupal.org/node/2919603
