### ISSUE TITLE
Add a trait for making purchasable entities subscribeable

### ISSUE THREAD

**Issue by dawehner** [bojanz/commerce_recurring#2]
> we then need an AllowSubscriptions trait that will attach a billing_schedules reference field to variations

**Comment by bojanz** [comment]
Shipping examples:
https://github.com/drupalcommerce/commerce_shipping/blob/8.x-2.x/src/Plugin/Commerce/EntityTrait/PurchasableEntityShippable.php
https://github.com/drupalcommerce/commerce_shipping/blob/8.x-2.x/commerce_shipping.module#L18

Note me trying to prevent the word "subscribeable" from entering the codebase.

**Comment by bojanz** [comment]
This got done.
