### ISSUE TITLE
Plan changes

### ISSUE THREAD

**Issue by dawehner** [bojanz/commerce_recurring#22]
We want to allow changes of the plan over time:

Usecases:

> going from a Basic to a Premium plan, or from a monthly to a yearly schedule

Things to take into account:

* Should we deal with the current billing cycle? This is postponed for now. Any changes are just taken into account for the next billing cycle
* Are any queue items maybe no longer valid? Due to the previous point, we just have valid queue items in the advanced queue

### Needed steps to update a plan

* Ensure the subscriptions are updated accordingly
* Ensure the billing schedules are updated

### Open questions

* How does the user changes the purchased entity? Is this something sites would provide an UI for?
   => NO UI

#### Summary by bojanz

> Recurring orders for prepaid subscriptions always charge for the next cycle. If the next cycle is scheduled to change, the refresh logic needs to take that into account, and switch immediately

> that way at the end of Feb we pay for the next desired period, which is a year or whatever

> Recurring orders for postpaid subscriptions always charge for the current period, so there we just close the order and change the next one

**Comment by wizonesolutions** [comment]
Kazanir wanted to look into providing a  UI if possible. My idea was to
provide confirmation forms that builders could link to for plan changes.

Maybe a default view could act as a starter, but plan management is often
rather custom, and I'm not sure how much Recurring should try to solve.

20. okt. 2017 17:25 je oseba "Daniel Wehner" <notifications@github.com>
napisala:

**Comment by bojanz** [comment]
Now tracked on d.o: https://www.drupal.org/node/2919600
