### ISSUE TITLE
Add Billing Schedule:  The "noop" plugin does not exist

### ISSUE THREAD

**Issue by t2-thirdwave** [bojanz/commerce_recurring#25]
When clicking the "Add Billing Schedule" button following installation:

> Add Billing Schedule: Uncaught PHP Exception Drupal\Component\Plugin\Exception\PluginNotFoundException: "The "noop" plugin does not exist." at /webroot/core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php line 52 

Using:
- Drupal 8.4.0
- PHP 7.1.8
- Apache 2.2.32
- MySQL 5.6.35

**Comment by dawehner** [comment]
I did a quick PR to fix this problem.

**Comment by bojanz** [comment]
Thank you!

**Comment by t2-thirdwave** [comment]
Hey guys, am I doing something wrong here?  Is there something I need to do prior to adding a Billing Schedule?

I pulled the updated module this morning and got the same error:

> [08-Nov-2017 11:10:40 America/Chicago] Uncaught PHP Exception Drupal\Component\Plugin\Exception\PluginNotFoundException: "The "noop" plugin does not exist." at /webroot/web/core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php line 52

using:

- Drupal 8.4.2
- Drupal Commerce 8.x-2.0
- PHP 7.1.8
- Apache 2.2.32
- MySQL 5.6.35

**Comment by bojanz** [comment]
There are no references to a noop plugin anywhere in the codebase anymore.
You probably have an old broken entity that you need to delete.

Also, you can't run recurring on Commerce 2.0, it has been rebased on 2.1 (for the new Interval object)

**Comment by t2-thirdwave** [comment]
I see.  Thanks for the fast response.  I'll update Commerce and try again.

**Comment by t2-thirdwave** [comment]
Same result from clean install.  No possibility of an old broken entity, unless it's in core.

Please advise.

- Drupal 8.4.2
- Drupal Commerce 8.x-2.1
- PHP 7.1.8
- Apache 2.2.32
- MySQL 5.6.35
