### ISSUE TITLE
Swap out the getOwner call in SubscriptionListBuilder

### ISSUE THREAD

**Issue by CameronLambTBX** [bojanz/commerce_recurring#27]
I get the following when tring to manually create a subscription through the UI:
```
Error: Call to undefined method Drupal\commerce_recurring\Entity\Subscription::getOwner()
in Drupal\commerce_recurring\SubscriptionListBuilder->buildRow()
(line 43 of modules/contrib/commerce_recurring/src/SubscriptionListBuilder.php).
```
I assume that all we need to do is swap getOwner for getCustomer?

**Comment by dawehner** [comment]
That makes sense, as we see some tests for the UI are always helpful as well.
Do you want to create PR?
