### ISSUE TITLE
Implement subscription & subscription type

### ISSUE THREAD

**Issue by bojanz** [bojanz/commerce_recurring#5]
Billing Schedule & Plan (variation) -> Subscription -> Recurring order.

The subscription is a content entity.
The subscription type is a bundle plugin.

Subscription fields:
- billing_schedule
- uid
- payment_method
- purchased_entity
- amount
- others

More details to follow.

**Comment by dawehner** [comment]
Working on this issue now

**Comment by dawehner** [comment]
We have resolved that in the meantime.
