### ISSUE TITLE
Implement usage tracking

### ISSUE THREAD

**Issue by bojanz** [bojanz/commerce_recurring#8]
http://cgit.drupalcode.org/commerce_license_billing/tree/commerce_license_billing.install#n104
http://cgit.drupalcode.org/commerce_license_billing/tree/commerce_license_billing.module#n1568
http://cgit.drupalcode.org/commerce_license_billing/tree/plugins/usage_group
http://cgit.drupalcode.org/commerce_license_billing/tree/tests/plugins/license_type/CommerceLicenseBillingTest.class.php#n11

Related D8 example:
https://github.com/drupalcommerce/commerce/blob/8.x-2.x/modules/promotion/src/PromotionUsageInterface.php
https://github.com/drupalcommerce/commerce/blob/8.x-2.x/modules/promotion/src/PromotionUsage.php

Implementation plan to be added.

Open question: How do we name the plugin type? Keep UsageGroup (D7)? Use UsageType (Kazanir's current code)? I am leaning towards UsageType right now, but wanted it to be rediscussed.

**Comment by wizonesolutions** [comment]
+1 `UsageType`, assuming we are talking about `counter` and `gauge`. I also never really understood what usage groups (the discrete SKU/usage type mappings in CLB) were actually grouping. Nearly every "group" only mapped to one D7 product SKU.

**Comment by bojanz** [comment]
Now tracked on d.o: https://www.drupal.org/node/2919598
